/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_px5_io_BTJoystick */

#ifndef _Included_org_px5_io_BTJoystick
#define _Included_org_px5_io_BTJoystick
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_px5_io_BTJoystick
 * Method:    jsInput
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_px5_io_BTJoystick_jsInput
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
